-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Create Users Table
create table public.users (
  id uuid default uuid_generate_v4() primary key,
  email text unique not null,
  password_hash text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Gallery Images Table
create table public.gallery_images (
  id bigint generated by default as identity primary key,
  image_url text not null,
  caption text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Site Settings Table
create table public.site_settings (
  key text primary key,
  value text not null
);

-- 4. Enable Row Level Security (RLS)
alter table public.users enable row level security;
alter table public.gallery_images enable row level security;
alter table public.site_settings enable row level security;

-- 5. Create Policies (Allow public read, Service Role full access)

-- Gallery Images Policies
create policy "Allow public read access to gallery"
  on public.gallery_images for select
  to anon
  using (true);

create policy "Allow full access to service role"
  on public.gallery_images for all
  to service_role
  using (true)
  with check (true);

-- Site Settings Policies
create policy "Allow public read access to settings"
  on public.site_settings for select
  to anon
  using (true);

create policy "Allow full access to service role"
  on public.site_settings for all
  to service_role
  using (true)
  with check (true);

-- Users Policies (Only service role can read/write)
create policy "Allow full access to service role"
  on public.users for all
  to service_role
  using (true)
  with check (true);

-- 6. Storage Bucket Setup
insert into storage.buckets (id, name, public)
values ('gallery', 'gallery', true)
on conflict (id) do nothing;

-- 7. Storage Policies
create policy "Public Access"
  on storage.objects for select
  to public
  using ( bucket_id = 'gallery' );

create policy "Service Role Upload"
  on storage.objects for insert
  to service_role
  with check ( bucket_id = 'gallery' );

create policy "Service Role Delete"
  on storage.objects for delete
  to service_role
  using ( bucket_id = 'gallery' );
